[package]
name = "log_indexer"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
elasticsearch = "8.5.0-alpha.1"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"